[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "7c187552-78e3-4c90-837c-0bb557fc1939"

# Settings in the [build] context are global and are applied to all contexts
[build]
  publish = "dist/"
  command = "yarn build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200